/** @format */

export const availableLanguages = [
	["af", "Afrikaans"],
	["al", "Shqip"],
	["ar", "عربى"],
	["az", "Azərbaycan dilində"],
	["bg", "Български"],
	["cz", "Čeština"],
	["da", "Dansk"],
	["de", "Deutsch"],
	["el", "Ελληνικά"],
	["fi", "Suomi"],
	["fr", "Français"],
	["he", "עברית"],
	["hi", "हिन्दी"],
	["hr", "Hrvatski"],
	["hu", "Magyar"],
	["id", "Bahasa Indonesia"],
	["it", "Italiano"],
	["ja", "日本語"],
	["kr", "한국어"],
	["no", "Norsk"],
	["nl", "Nederlands"],
	["pl", "Polski"],
	["pt", "Português"],
	["ro", "Română"],
	["ru", "Русский"],
	["sv", "Svenska"],
	["sp", "Español"],
	["sr", "Српски"],
	["th", "ไทย"],
	["tr", "Türkçe"],
	["uk", "Українська"],
	["vi", "Tiếng Việt"],
	["zh_cn", "简体中文"]
];
